title: Sistemas Robóticos - CFP Nº8
description: Sitio web con material teórico - práctico sobre el curso. Como funcionan los sistemas embebidos, como se vinculan con la electrónica, como se programan y como se desarrollan.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one